/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.projetointegrador02.windows;

import com.projetointegrador02.Env;
import com.projetointegrador02.database.DatabaseConnection;
import com.projetointegrador02.database.UserCrud;
import com.projetointegrador02.entities.User;
import com.projetointegrador02.windows.contacts.FormContAdd;
import com.projetointegrador02.windows.users.FormLogin;
import com.projetointegrador02.entities.Contact;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Usuario
 */
public class Home extends javax.swing.JFrame {
    private User currentUser;
    /** Creates new form Home
     * @param currentUser */
 
    public Home(User currentUser) {
        initComponents();
        this.currentUser = currentUser;
        scrollUserTable.setVisible(false);
        deleteBtn.setVisible(false);
        deselectBtn.setVisible(false);
    }
    public Home() {
        initComponents();
    }
    
    private void loadTable() throws SQLException {
        scrollUserTable.setVisible(true);
    
        DatabaseConnection databaseConnection = new DatabaseConnection(
            "root", Env.getPass(), "manager_messages", "localhost", 3306);
        UserCrud userCrud = new UserCrud(databaseConnection);
        Vector<User> users = userCrud.loadUsers();
        DefaultTableModel model = (DefaultTableModel) userTable.getModel();
        for (User user : users) {
            String userName = user.getUserName();
            if (user.getId() == currentUser.getId()) {
                userName = currentUser.getUserName().concat("[você]"); 
            }
            model.addRow(new Object[]{
            user.getId(), userName 
            });             
        }
        deleteBtn.setVisible(true);
        loadBtn.setEnabled(false); 
        deselectBtn.setVisible(true);
    }
    
    private void deleteCurrentUser() throws SQLException {
        DatabaseConnection databaseConnection = new DatabaseConnection(
            "root", Env.getPass(), "manager_messages", "localhost", 3306);
        
        UserCrud userCrud = new UserCrud(databaseConnection);
        userCrud.delete((int) currentUser.getId());

        scrollUserTable.setVisible(false);
        deleteBtn.setVisible(false);
        addContBtn.setEnabled(false);
        JOptionPane.showMessageDialog(rootPane,
            "Usuário excluido com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        userPanel = new javax.swing.JPanel();
        scrollUserTable = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        loadBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        addContBtn = new javax.swing.JButton();
        addUserBtn = new javax.swing.JButton();
        deselectBtn = new javax.swing.JButton();
        contPanel = new javax.swing.JPanel();
        userPanel1 = new javax.swing.JPanel();
        fieldNome = new javax.swing.JTextField();
        btnExc = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        btnPes = new javax.swing.JButton();
        lbNome = new javax.swing.JLabel();
        btnPes1 = new javax.swing.JButton();
        messagePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manager Messages");
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tabbedPane.setBackground(new java.awt.Color(0, 51, 153));
        tabbedPane.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabbedPane.setForeground(new java.awt.Color(255, 255, 255));
        tabbedPane.setToolTipText("");
        tabbedPane.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        userPanel.setBackground(new java.awt.Color(0, 51, 153));
        userPanel.setPreferredSize(new java.awt.Dimension(600, 350));

        userTable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Usuário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        userTable.setAlignmentX(1.0F);
        userTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        userTable.setGridColor(new java.awt.Color(102, 153, 255));
        userTable.setRowHeight(25);
        userTable.setSelectionBackground(new java.awt.Color(0, 102, 204));
        userTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTableMouseClicked(evt);
            }
        });
        scrollUserTable.setViewportView(userTable);
        if (userTable.getColumnModel().getColumnCount() > 0) {
            userTable.getColumnModel().getColumn(0).setResizable(false);
            userTable.getColumnModel().getColumn(0).setPreferredWidth(5);
            userTable.getColumnModel().getColumn(1).setPreferredWidth(95);
        }

        loadBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        loadBtn.setText("Carregar Usuários");
        loadBtn.setToolTipText("Carrega a lista com todos os usuários. Só pode ser feito uma vez.");
        loadBtn.setBorder(null);
        loadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(255, 51, 51));
        deleteBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setActionCommand("Excluir o Seu Usuário");
        deleteBtn.setLabel("Excluir o Seu Usuário");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        addContBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        addContBtn.setText("Adicionar Contato");
        addContBtn.setToolTipText("Adiciona um usuário  na sua lista de contatos.");
        addContBtn.setBorder(null);
        addContBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addContBtnActionPerformed(evt);
            }
        });

        addUserBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        addUserBtn.setText("Nova Sessão ");
        addUserBtn.setToolTipText("Abre uma nova janela de login. Atenção: ao fechar \nqualquer menu principal todas as sessões serão encerradas!");
        addUserBtn.setBorder(null);
        addUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserBtnActionPerformed(evt);
            }
        });

        deselectBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        deselectBtn.setText("Desfazer Seleção");
        deselectBtn.setToolTipText("Retira a seleção da tabela");
        deselectBtn.setBorder(null);
        deselectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deselectBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollUserTable, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addContBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addUserBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(loadBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deselectBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollUserTable, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addComponent(loadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addContBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deselectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        tabbedPane.addTab("   Usuários   ", userPanel);

        userPanel1.setBackground(new java.awt.Color(0, 51, 153));

        fieldNome.setColumns(12);
        fieldNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNomeActionPerformed(evt);
            }
        });

        btnExc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnExc.setText("Excluir");
        btnExc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEdit.setText("Editar");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        list.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Contato 1", "Contato 1", "Contato 3", "Contato 4", "Contato 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(list);

        btnPes.setText("🔍");
        btnPes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesActionPerformed(evt);
            }
        });

        lbNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbNome.setForeground(new java.awt.Color(255, 255, 255));
        lbNome.setText("Nome:");

        btnPes1.setText("🔍");
        btnPes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPes1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userPanel1Layout = new javax.swing.GroupLayout(userPanel1);
        userPanel1.setLayout(userPanel1Layout);
        userPanel1Layout.setHorizontalGroup(
            userPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(userPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(userPanel1Layout.createSequentialGroup()
                        .addComponent(lbNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fieldNome)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(userPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(userPanel1Layout.createSequentialGroup()
                        .addComponent(btnPes, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPes1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        userPanel1Layout.setVerticalGroup(
            userPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(userPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(userPanel1Layout.createSequentialGroup()
                        .addGroup(userPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPes, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNome)
                            .addComponent(btnPes1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(btnExc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEdit)))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout contPanelLayout = new javax.swing.GroupLayout(contPanel);
        contPanel.setLayout(contPanelLayout);
        contPanelLayout.setHorizontalGroup(
            contPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        contPanelLayout.setVerticalGroup(
            contPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabbedPane.addTab("   Contatos   ", contPanel);

        messagePanel.setBackground(new java.awt.Color(0, 51, 153));

        javax.swing.GroupLayout messagePanelLayout = new javax.swing.GroupLayout(messagePanel);
        messagePanel.setLayout(messagePanelLayout);
        messagePanelLayout.setHorizontalGroup(
            messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
        );
        messagePanelLayout.setVerticalGroup(
            messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 354, Short.MAX_VALUE)
        );

        tabbedPane.addTab("   Mensagens   ", messagePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       
        int end = JOptionPane.showConfirmDialog(rootPane,
                "Fechar o menu principal encerrará a sessão e a aplicação.\nTem certeza que deseja fazer isso?",
                "Encerrar Programa", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE
        );
        if (end == 0) {
            this.setVisible(false);
            System.exit(0);
        } else {
            this.getDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing

    private void loadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBtnActionPerformed
        try {   
            loadTable();        
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, 
                "Erro na consulta aconteceu! " + ex.getErrorCode() + ex.getMessage(),
                "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_loadBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int end = JOptionPane.showConfirmDialog(rootPane, String.format(         
            "O usuário '%s' será excluido de todas as listas de contatos.\n Tem certeza que deseja fazer isso?",
            currentUser.getUserName().toUpperCase()),
            "Excluir Usuário", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        
        if (end == 0) {
            try {
                deleteCurrentUser();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, 
                    "Erro inesperado aconteceu! " + ex.getErrorCode() + ex.getMessage(),
                    "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    private void addContBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addContBtnActionPerformed
        FormContAdd formContAdd;
        int rowSelected = userTable.getSelectedRow();
        if (rowSelected != -1) {            
            formContAdd = new FormContAdd(new User(this.currentUser.getId()), new Contact( 
                (int) userTable.getValueAt(rowSelected, 0)));           
        } else {
            User current = new User(currentUser.getId());
            formContAdd = new FormContAdd(current);
        }
        formContAdd.setVisible(true);
    }//GEN-LAST:event_addContBtnActionPerformed

    private void addUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserBtnActionPerformed
        FormLogin formLogin = new FormLogin();
        formLogin.setVisible(true);
    }//GEN-LAST:event_addUserBtnActionPerformed

    private void fieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNomeActionPerformed

    private void btnExcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcActionPerformed
        int end = JOptionPane.showConfirmDialog(rootPane,
            "Tem certeza que deseja excluir o contato?", 
            "Excluir Contato", WIDTH, JOptionPane.WARNING_MESSAGE);
        if (end == 0) {
            this.setVisible(false);
            JOptionPane.showMessageDialog(rootPane, "Contato excluído com sucesso.");
        } else {
            this.setVisible(true);
        }
    }//GEN-LAST:event_btnExcActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        FormContAdd formContAdd = new FormContAdd();
        formContAdd.setVisible(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnPesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnPesActionPerformed

    private void btnPes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPes1ActionPerformed

    private void userTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTableMouseClicked

    }//GEN-LAST:event_userTableMouseClicked

    private void deselectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deselectBtnActionPerformed
        int rowSelected = userTable.getSelectedRow();
        if (rowSelected != -1) {
            userTable.clearSelection();
        }
    }//GEN-LAST:event_deselectBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Home().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addContBtn;
    private javax.swing.JButton addUserBtn;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExc;
    private javax.swing.JButton btnPes;
    private javax.swing.JButton btnPes1;
    private javax.swing.JPanel contPanel;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton deselectBtn;
    private javax.swing.JTextField fieldNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbNome;
    private javax.swing.JList<String> list;
    private javax.swing.JButton loadBtn;
    private javax.swing.JPanel messagePanel;
    private javax.swing.JScrollPane scrollUserTable;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JPanel userPanel;
    private javax.swing.JPanel userPanel1;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables

    private void getDefaultCloseOperation(int DO_NOTHING_ON_CLOSE) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
