/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.projetointegrador02.windows.users;

import com.projetointegrador02.validators.TreatmentException;
import com.projetointegrador02.database.DatabaseConnection;
import com.projetointegrador02.database.UserCrud;
import com.projetointegrador02.entities.User;
import com.projetointegrador02.Env;
import java.sql.SQLException;
import javax.swing.JOptionPane;



/**
 *
 * @author Usuario
 */
public class FormUsuAdd extends javax.swing.JFrame {
    
    

    /**
     * Creates new form FormUsuAdd
     */
    public FormUsuAdd() {
        initComponents();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        userField = new javax.swing.JTextField();
        lbUser = new javax.swing.JLabel();
        lbPassword = new javax.swing.JLabel();
        btnAddUser = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        doublePasswordField = new javax.swing.JPasswordField();
        lbDoublePassword = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar Usuário");

        userField.setColumns(10);
        userField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        userField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        userField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userFieldActionPerformed(evt);
            }
        });

        lbUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbUser.setLabelFor(userField);
        lbUser.setText("Usuário:");

        lbPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbPassword.setLabelFor(passwordField);
        lbPassword.setText("Senha:");

        btnAddUser.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnAddUser.setText("ADICIONAR USUÁRIO");
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });

        passwordField.setColumns(10);
        passwordField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        doublePasswordField.setColumns(10);
        doublePasswordField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        doublePasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doublePasswordFieldActionPerformed(evt);
            }
        });

        lbDoublePassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbDoublePassword.setLabelFor(doublePasswordField);
        lbDoublePassword.setText("Confirma:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnAddUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbDoublePassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(doublePasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbUser)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(lbPassword)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUser)
                    .addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPassword)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doublePasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDoublePassword))
                .addGap(18, 18, 18)
                .addComponent(btnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        // TODO add your handling code here:
        
        /*JOptionPane jo = new JOptionPane();
        if ((this.fieldEmail.getText().equals(noneData)) || (this.fieldUsuario.getText().equals(noneData)) || (this.passwordField.getText().equals(noneData))) {
            jo.showMessageDialog(rootPane, "Preencha todos os campos corretamente!",
                "Campos inválidos", JOptionPane.ERROR_MESSAGE);
        } else {
            jo.showMessageDialog(rootPane, "Usuário adicionado com sucesso!",
                "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
        }*/
        try {
            validateRequiredFields();
            validateDoublePassword();
            
            DatabaseConnection databaseConnection = new DatabaseConnection(
                "root", Env.getPass(), "manager_messages", "localhost", 3306);
            User user = new User(userField.getText(), passwordField.getText());
            UserCrud userCrud = new UserCrud(databaseConnection);
            userCrud.save(user);
            JOptionPane.showMessageDialog(rootPane, "Usuário cadastrado com sucesso!");
            clean();
            this.setVisible(false);
        } catch (TreatmentException treatmentException) {
            JOptionPane.showMessageDialog(rootPane, treatmentException.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro inesperado aconteceu! " + ex.getMessage());
            
        }
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void doublePasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doublePasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doublePasswordFieldActionPerformed

    private void userFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUsuAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUsuAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUsuAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUsuAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUsuAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUser;
    private javax.swing.JPasswordField doublePasswordField;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JLabel lbDoublePassword;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbUser;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField userField;
    // End of variables declaration//GEN-END:variables
     private void validateRequiredFields() throws TreatmentException {
        if ((userField.getText().isBlank())||(passwordField.getText().isBlank())) {
            throw new TreatmentException("Todos os campos são obrigatórios!");
        }
        
    }

    private void validateDoublePassword() throws TreatmentException {
        if (!passwordField.getText().equals(doublePasswordField.getText())) {
            throw new TreatmentException("Campo senha deve ser igual ao confirmação de senha!");
        }
    }
    
    private void uniqueUser() throws TreatmentException {
        
    }
    private void clean() {
        userField.setText("");
        passwordField.setText("");
        doublePasswordField.setText("");
    }
}
